project_id = "hbjobpbiordnwflfhjnu"

[functions.check-breached-password]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.process-recurring-transactions]
verify_jwt = false

[functions.create-pagarme-subscription]
verify_jwt = true

[functions.pagarme-webhook]
verify_jwt = false