// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbjobpbiordnwflfhjnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhiam9icGJpb3JkbndmbGZoam51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMTc4NDksImV4cCI6MjA2NzY5Mzg0OX0.xWd7SrnTzSQ_Ti535-RtBwdB9kjHTO4vGbkpDyjuMh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});